name: Build relayd for WNDR4300 (mips_24kc)

on:
  workflow_dispatch:

jobs:
  build-relayd:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses-dev libssl-dev python3 python3-pip rsync unzip zlib1g-dev file wget libelf-dev ecj fastjar java-propose-classpath libglib2.0-dev libfdt-dev python3-setuptools

      - name: Checkout OpenWrt
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add relayd package config
        run: |
          cd openwrt
          echo 'CONFIG_PACKAGE_relayd=m' >> .config
          echo 'CONFIG_PACKAGE_luci-proto-relay=m' >> .config
          echo 'CONFIG_ALL_KMODS=n' >> .config
          echo 'CONFIG_ALL=n' >> .config
          echo 'CONFIG_DEVEL=n' >> .config
          echo 'CONFIG_CCACHE=n' >> .config
          echo 'CONFIG_TARGET_ath79=y' >> .config
          echo 'CONFIG_TARGET_ath79_nand=y' >> .config
          echo 'CONFIG_TARGET_ath79_nand_DEVICE_wndr4300=y' >> .config
          make defconfig

      - name: Download all sources
        run: |
          cd openwrt
          make download -j$(nproc) V=s

      - name: Compile relayd package
        run: |
          cd openwrt
          make package/network/services/relayd/compile V=s -j$(nproc)
          make package/network/services/relayd/install V=s -j$(nproc)
          make package/network/services/relayd/index
          make package/network/services/relayd/clean

          make package/feeds/luci/luci-proto-relay/compile V=s -j$(nproc)
          make package/feeds/luci/luci-proto-relay/install V=s -j$(nproc)

      - name: Upload .ipk packages
        uses: actions/upload-artifact@v4
        with:
          name: relayd-packages
          path: |
            openwrt/bin/packages/mips_24kc/base/relayd_*.ipk
            openwrt/bin/packages/mips_24kc/luci/luci-proto-relay_*.ipk
