name: Build relayd for WNDR4300 (mips_74kc, OpenWrt 22.02.2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 安装基础依赖
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3 unzip zlib1g-dev file wget \
          libelf-dev ccache rsync subversion libtool python3-pip

    - name: 克隆 OpenWrt 源码（v22.02.2）
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v22.02.2

    - name: 初始化 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 配置 WNDR4300 架构 + 启用 relayd 软件包
      working-directory: ./openwrt
      run: |
        echo "CONFIG_TARGET_ath79=y" > .config
        echo "CONFIG_TARGET_ath79_nand=y" >> .config
        echo "CONFIG_TARGET_ath79_nand_DEVICE_wndr4300=y" >> .config
        echo "CONFIG_PACKAGE_relayd=y" >> .config
        make defconfig

    - name: 下载依赖
      working-directory: ./openwrt
      run: make download -j$(nproc)

    - name: 编译 relayd 软件包
      working-directory: ./openwrt
      run: |
        make package/relayd/compile V=s -j$(nproc)

    - name: 上传编译好的 .ipk 软件包
      uses: actions/upload-artifact@v4
      with:
        name: relayd-ipk
        path: |
          openwrt/bin/packages/mips_*/base/relayd_*.ipk
