name: Build relayd for WNDR4300 (mips_74kc, OpenWrt R22.2.2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3 unzip zlib1g-dev file wget libelf-dev ccache \
        rsync subversion libtool python3-pip

    - name: 克隆 OpenWrt R22.2.2 源码
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git checkout v22.02.2

    - name: 更新 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 选择目标配置（WNDR4300 - mips_74kc）
      working-directory: ./openwrt
      run: |
        make defconfig
        echo -e "CONFIG_TARGET_ath79=y\nCONFIG_TARGET_ath79_nand=y\nCONFIG_TARGET_ath79_nand_DEVICE_wndr4300=y\nCONFIG_PACKAGE_relayd=y" >> .config
        make defconfig

    - name: 下载依赖
      working-directory: ./openwrt
      run: make download -j8

    - name: 编译 relayd 软件包
      working-directory: ./openwrt
      run: make package/relayd/compile V=s -j$(nproc)

    - name: 上传 relayd 软件包（.ipk）
      uses: actions/upload-artifact@v4
      with:
        name: relayd-ipk
        path: openwrt/bin/packages/mips_*/base/relayd_*.ipk
